import PdfPrinter from 'pdfmake';
import type { TDocumentDefinitions, Content } from 'pdfmake/interfaces';
import { FinancialStatement, ReportNode, RatioResult } from '../../shared/types';
import { formatINR } from '../../shared/money';

// pdfmake needs font descriptors. We ship the standard 14 (Helvetica) which
// requires no embedded font files — ideal for a fully-offline desktop app.
const fonts = {
  Helvetica: {
    normal: 'Helvetica',
    bold: 'Helvetica-Bold',
    italics: 'Helvetica-Oblique',
    bolditalics: 'Helvetica-BoldOblique',
  },
};

function tableBody(nodes: ReportNode[]): any[] {
  const rows: any[] = [];
  const walk = (list: ReportNode[]) => {
    for (const n of list) {
      const isHead = !!n.children && n.level === 0;
      rows.push([
        {
          text: '    '.repeat(n.level) + n.label,
          bold: isHead,
          margin: [0, 1, 0, 1],
        },
        { text: n.noteRef ? String(n.noteRef) : '', alignment: 'center' },
        { text: formatINR(n.amount, { showZero: true }), alignment: 'right', bold: isHead },
      ]);
      if (n.children) walk(n.children);
    }
  };
  walk(nodes);
  return rows;
}

function statementContent(st: FinancialStatement): Content[] {
  return [
    { text: st.companyName, style: 'company' },
    {
      text: `${st.title} — ${st.division === 'DIV_II' ? 'Division II (Ind AS)' : 'Division I (IGAAP)'}`,
      style: 'subtitle',
    },
    { text: `As at ${st.toDate}`, style: 'subtitle', margin: [0, 0, 0, 8] },
    {
      table: {
        headerRows: 1,
        widths: ['*', 30, 90],
        body: [
          [
            { text: 'Particulars', bold: true },
            { text: 'Note', bold: true, alignment: 'center' },
            { text: 'Amount (₹)', bold: true, alignment: 'right' },
          ],
          ...tableBody(st.nodes),
          [
            { text: 'TOTAL', bold: true },
            '',
            { text: formatINR(st.total, { showZero: true }), bold: true, alignment: 'right' },
          ],
        ],
      },
      layout: 'lightHorizontalLines',
    },
  ];
}

export function exportStatementsToPdf(
  statements: FinancialStatement[],
  ratios?: RatioResult[],
): Promise<Buffer> {
  const printer = new PdfPrinter(fonts);

  const content: Content[] = [];
  statements.forEach((st, i) => {
    if (i > 0) content.push({ text: '', pageBreak: 'before' });
    content.push(...statementContent(st));
  });

  if (ratios?.length) {
    content.push({ text: '', pageBreak: 'before' });
    content.push({ text: 'Statutory Ratios (Schedule III)', style: 'subtitle', margin: [0, 0, 0, 8] });
    content.push({
      table: {
        headerRows: 1,
        widths: ['*', 60, '*'],
        body: [
          [{ text: 'Ratio', bold: true }, { text: 'Value', bold: true }, { text: 'Formula', bold: true }],
          ...ratios.map((r) => [
            r.name,
            { text: r.value, alignment: 'right' as const },
            { text: r.formula, italics: true },
          ]),
        ],
      },
      layout: 'lightHorizontalLines',
    } as Content);
  }

  const docDef: TDocumentDefinitions = {
    pageSize: 'A4',
    pageMargins: [40, 40, 40, 50],
    defaultStyle: { font: 'Helvetica', fontSize: 9 },
    styles: {
      company: { fontSize: 15, bold: true },
      subtitle: { fontSize: 10, italics: true, color: '#444' },
    },
    footer: (page, total) => ({
      text: `Page ${page} of ${total}  •  Generated by GeniusAI Infinity`,
      alignment: 'center', fontSize: 7, color: '#888', margin: [0, 10, 0, 0],
    }),
    content,
  };

  return new Promise((resolve, reject) => {
    const doc = printer.createPdfKitDocument(docDef);
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}
